/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrgentRouteImport } from './routes/urgent'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as FinanceTenantsRouteImport } from './routes/finance-tenants'
import { Route as FinanceSettingsRouteImport } from './routes/finance-settings'
import { Route as FinanceReportsRouteImport } from './routes/finance-reports'
import { Route as FinanceRemindersRouteImport } from './routes/finance-reminders'
import { Route as FinanceReceiptsRouteImport } from './routes/finance-receipts'
import { Route as FinancePaymentsRouteImport } from './routes/finance-payments'
import { Route as FinanceOverdueRouteImport } from './routes/finance-overdue'
import { Route as FinanceOutstandingRouteImport } from './routes/finance-outstanding'
import { Route as FinanceNotificationsRouteImport } from './routes/finance-notifications'
import { Route as FinanceLeaseRenewalsRouteImport } from './routes/finance-lease-renewals'
import { Route as FinanceInvoicesRouteImport } from './routes/finance-invoices'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as CompletionsRouteImport } from './routes/completions'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const UrgentRoute = UrgentRouteImport.update({
  id: '/urgent',
  path: '/urgent',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTenantsRoute = FinanceTenantsRouteImport.update({
  id: '/finance-tenants',
  path: '/finance-tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/finance-settings',
  path: '/finance-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/finance-reports',
  path: '/finance-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRemindersRoute = FinanceRemindersRouteImport.update({
  id: '/finance-reminders',
  path: '/finance-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReceiptsRoute = FinanceReceiptsRouteImport.update({
  id: '/finance-receipts',
  path: '/finance-receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance-payments',
  path: '/finance-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceOverdueRoute = FinanceOverdueRouteImport.update({
  id: '/finance-overdue',
  path: '/finance-overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceOutstandingRoute = FinanceOutstandingRouteImport.update({
  id: '/finance-outstanding',
  path: '/finance-outstanding',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceNotificationsRoute = FinanceNotificationsRouteImport.update({
  id: '/finance-notifications',
  path: '/finance-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceLeaseRenewalsRoute = FinanceLeaseRenewalsRouteImport.update({
  id: '/finance-lease-renewals',
  path: '/finance-lease-renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/finance-invoices',
  path: '/finance-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletionsRoute = CompletionsRouteImport.update({
  id: '/completions',
  path: '/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/completions': typeof CompletionsRoute
  '/escalations': typeof EscalationsRoute
  '/finance': typeof FinanceRoute
  '/finance-invoices': typeof FinanceInvoicesRoute
  '/finance-lease-renewals': typeof FinanceLeaseRenewalsRoute
  '/finance-notifications': typeof FinanceNotificationsRoute
  '/finance-outstanding': typeof FinanceOutstandingRoute
  '/finance-overdue': typeof FinanceOverdueRoute
  '/finance-payments': typeof FinancePaymentsRoute
  '/finance-receipts': typeof FinanceReceiptsRoute
  '/finance-reminders': typeof FinanceRemindersRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-settings': typeof FinanceSettingsRoute
  '/finance-tenants': typeof FinanceTenantsRoute
  '/managers': typeof ManagersRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
  '/urgent': typeof UrgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/completions': typeof CompletionsRoute
  '/escalations': typeof EscalationsRoute
  '/finance': typeof FinanceRoute
  '/finance-invoices': typeof FinanceInvoicesRoute
  '/finance-lease-renewals': typeof FinanceLeaseRenewalsRoute
  '/finance-notifications': typeof FinanceNotificationsRoute
  '/finance-outstanding': typeof FinanceOutstandingRoute
  '/finance-overdue': typeof FinanceOverdueRoute
  '/finance-payments': typeof FinancePaymentsRoute
  '/finance-receipts': typeof FinanceReceiptsRoute
  '/finance-reminders': typeof FinanceRemindersRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-settings': typeof FinanceSettingsRoute
  '/finance-tenants': typeof FinanceTenantsRoute
  '/managers': typeof ManagersRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
  '/urgent': typeof UrgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/completions': typeof CompletionsRoute
  '/escalations': typeof EscalationsRoute
  '/finance': typeof FinanceRoute
  '/finance-invoices': typeof FinanceInvoicesRoute
  '/finance-lease-renewals': typeof FinanceLeaseRenewalsRoute
  '/finance-notifications': typeof FinanceNotificationsRoute
  '/finance-outstanding': typeof FinanceOutstandingRoute
  '/finance-overdue': typeof FinanceOverdueRoute
  '/finance-payments': typeof FinancePaymentsRoute
  '/finance-receipts': typeof FinanceReceiptsRoute
  '/finance-reminders': typeof FinanceRemindersRoute
  '/finance-reports': typeof FinanceReportsRoute
  '/finance-settings': typeof FinanceSettingsRoute
  '/finance-tenants': typeof FinanceTenantsRoute
  '/managers': typeof ManagersRoute
  '/properties': typeof PropertiesRoute
  '/reports': typeof ReportsRoute
  '/tickets': typeof TicketsRoute
  '/urgent': typeof UrgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/completions'
    | '/escalations'
    | '/finance'
    | '/finance-invoices'
    | '/finance-lease-renewals'
    | '/finance-notifications'
    | '/finance-outstanding'
    | '/finance-overdue'
    | '/finance-payments'
    | '/finance-receipts'
    | '/finance-reminders'
    | '/finance-reports'
    | '/finance-settings'
    | '/finance-tenants'
    | '/managers'
    | '/properties'
    | '/reports'
    | '/tickets'
    | '/urgent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/completions'
    | '/escalations'
    | '/finance'
    | '/finance-invoices'
    | '/finance-lease-renewals'
    | '/finance-notifications'
    | '/finance-outstanding'
    | '/finance-overdue'
    | '/finance-payments'
    | '/finance-receipts'
    | '/finance-reminders'
    | '/finance-reports'
    | '/finance-settings'
    | '/finance-tenants'
    | '/managers'
    | '/properties'
    | '/reports'
    | '/tickets'
    | '/urgent'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/announcements'
    | '/completions'
    | '/escalations'
    | '/finance'
    | '/finance-invoices'
    | '/finance-lease-renewals'
    | '/finance-notifications'
    | '/finance-outstanding'
    | '/finance-overdue'
    | '/finance-payments'
    | '/finance-receipts'
    | '/finance-reminders'
    | '/finance-reports'
    | '/finance-settings'
    | '/finance-tenants'
    | '/managers'
    | '/properties'
    | '/reports'
    | '/tickets'
    | '/urgent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CompletionsRoute: typeof CompletionsRoute
  EscalationsRoute: typeof EscalationsRoute
  FinanceRoute: typeof FinanceRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinanceLeaseRenewalsRoute: typeof FinanceLeaseRenewalsRoute
  FinanceNotificationsRoute: typeof FinanceNotificationsRoute
  FinanceOutstandingRoute: typeof FinanceOutstandingRoute
  FinanceOverdueRoute: typeof FinanceOverdueRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceReceiptsRoute: typeof FinanceReceiptsRoute
  FinanceRemindersRoute: typeof FinanceRemindersRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  FinanceTenantsRoute: typeof FinanceTenantsRoute
  ManagersRoute: typeof ManagersRoute
  PropertiesRoute: typeof PropertiesRoute
  ReportsRoute: typeof ReportsRoute
  TicketsRoute: typeof TicketsRoute
  UrgentRoute: typeof UrgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urgent': {
      id: '/urgent'
      path: '/urgent'
      fullPath: '/urgent'
      preLoaderRoute: typeof UrgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-tenants': {
      id: '/finance-tenants'
      path: '/finance-tenants'
      fullPath: '/finance-tenants'
      preLoaderRoute: typeof FinanceTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-settings': {
      id: '/finance-settings'
      path: '/finance-settings'
      fullPath: '/finance-settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-reports': {
      id: '/finance-reports'
      path: '/finance-reports'
      fullPath: '/finance-reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-reminders': {
      id: '/finance-reminders'
      path: '/finance-reminders'
      fullPath: '/finance-reminders'
      preLoaderRoute: typeof FinanceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-receipts': {
      id: '/finance-receipts'
      path: '/finance-receipts'
      fullPath: '/finance-receipts'
      preLoaderRoute: typeof FinanceReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-payments': {
      id: '/finance-payments'
      path: '/finance-payments'
      fullPath: '/finance-payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-overdue': {
      id: '/finance-overdue'
      path: '/finance-overdue'
      fullPath: '/finance-overdue'
      preLoaderRoute: typeof FinanceOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-outstanding': {
      id: '/finance-outstanding'
      path: '/finance-outstanding'
      fullPath: '/finance-outstanding'
      preLoaderRoute: typeof FinanceOutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-notifications': {
      id: '/finance-notifications'
      path: '/finance-notifications'
      fullPath: '/finance-notifications'
      preLoaderRoute: typeof FinanceNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-lease-renewals': {
      id: '/finance-lease-renewals'
      path: '/finance-lease-renewals'
      fullPath: '/finance-lease-renewals'
      preLoaderRoute: typeof FinanceLeaseRenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-invoices': {
      id: '/finance-invoices'
      path: '/finance-invoices'
      fullPath: '/finance-invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completions': {
      id: '/completions'
      path: '/completions'
      fullPath: '/completions'
      preLoaderRoute: typeof CompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CompletionsRoute: CompletionsRoute,
  EscalationsRoute: EscalationsRoute,
  FinanceRoute: FinanceRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinanceLeaseRenewalsRoute: FinanceLeaseRenewalsRoute,
  FinanceNotificationsRoute: FinanceNotificationsRoute,
  FinanceOutstandingRoute: FinanceOutstandingRoute,
  FinanceOverdueRoute: FinanceOverdueRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceReceiptsRoute: FinanceReceiptsRoute,
  FinanceRemindersRoute: FinanceRemindersRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  FinanceTenantsRoute: FinanceTenantsRoute,
  ManagersRoute: ManagersRoute,
  PropertiesRoute: PropertiesRoute,
  ReportsRoute: ReportsRoute,
  TicketsRoute: TicketsRoute,
  UrgentRoute: UrgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
